/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerateTextRouteImport } from './routes/generate-text'
import { Route as FakeDataRouteImport } from './routes/fake-data'
import { Route as IndexRouteImport } from './routes/index'

const GenerateTextRoute = GenerateTextRouteImport.update({
  id: '/generate-text',
  path: '/generate-text',
  getParentRoute: () => rootRouteImport,
} as any)
const FakeDataRoute = FakeDataRouteImport.update({
  id: '/fake-data',
  path: '/fake-data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fake-data': typeof FakeDataRoute
  '/generate-text': typeof GenerateTextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fake-data': typeof FakeDataRoute
  '/generate-text': typeof GenerateTextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fake-data': typeof FakeDataRoute
  '/generate-text': typeof GenerateTextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fake-data' | '/generate-text'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fake-data' | '/generate-text'
  id: '__root__' | '/' | '/fake-data' | '/generate-text'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FakeDataRoute: typeof FakeDataRoute
  GenerateTextRoute: typeof GenerateTextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generate-text': {
      id: '/generate-text'
      path: '/generate-text'
      fullPath: '/generate-text'
      preLoaderRoute: typeof GenerateTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fake-data': {
      id: '/fake-data'
      path: '/fake-data'
      fullPath: '/fake-data'
      preLoaderRoute: typeof FakeDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FakeDataRoute: FakeDataRoute,
  GenerateTextRoute: GenerateTextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
