/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MockDataRouteImport } from './routes/mock-data'
import { Route as GenerateTextRouteImport } from './routes/generate-text'
import { Route as IndexRouteImport } from './routes/index'

const MockDataRoute = MockDataRouteImport.update({
  id: '/mock-data',
  path: '/mock-data',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateTextRoute = GenerateTextRouteImport.update({
  id: '/generate-text',
  path: '/generate-text',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate-text': typeof GenerateTextRoute
  '/mock-data': typeof MockDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate-text': typeof GenerateTextRoute
  '/mock-data': typeof MockDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate-text': typeof GenerateTextRoute
  '/mock-data': typeof MockDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generate-text' | '/mock-data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generate-text' | '/mock-data'
  id: '__root__' | '/' | '/generate-text' | '/mock-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateTextRoute: typeof GenerateTextRoute
  MockDataRoute: typeof MockDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mock-data': {
      id: '/mock-data'
      path: '/mock-data'
      fullPath: '/mock-data'
      preLoaderRoute: typeof MockDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate-text': {
      id: '/generate-text'
      path: '/generate-text'
      fullPath: '/generate-text'
      preLoaderRoute: typeof GenerateTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateTextRoute: GenerateTextRoute,
  MockDataRoute: MockDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
